import Head from 'next/head'
import styles from '../styles/Home.module.css'

import Layout from '../components/Layout'

export default function Home(): JSX.Element {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <p>TEST</p>
      </Layout>
    </div>
  )
}
